name: location_example
description: Demonstrates how to use the location plugin.

dependencies:
  flutter:
    sdk: flutter
  location:
    path: ../
  url_launcher: ^6.0.0-nullsafety.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test: ^1.0.1

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
