name: location_web
description: The web implementation of the location plugin.
homepage: https://github.com/Lyokone/flutterlocation
version: 2.0.0-nullsafety.1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: LocationWebPlugin
        fileName: location_web.dart

dependencies:
  location_platform_interface:
    path: ../location_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http_parser: ^4.0.0-nullsafety
  js: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.10.0-nullsafety

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.22.0"
