name: location_platform_interface
description: A common platform interface for the location plugin.
homepage: https://github.com/Lyokone/flutterlocation
version: 2.0.0-nullsafety.1

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^1.1.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety
  pedantic: ^1.10.0-nullsafety

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.22.0"
