name: location
description: A Flutter plugin to easily handle realtime location in iOS and Android. Provides settings for optimizing performance or battery.
version: 4.0.0-nullsafety.1
author: Guillaume Bernos <guillaume@bernos.dev>
homepage: https://github.com/Lyokone/flutterlocation

flutter:
  plugin:
    platforms:
      android:
        package: com.lyokone.location
        pluginClass: LocationPlugin
      ios:
        pluginClass: LocationPlugin
      macos:
        pluginClass: LocationPlugin
      web:
        default_package: location_web

dependencies:
  flutter:
    sdk: flutter
  location_platform_interface:
    path: ../location_platform_interface
  location_web:
    path: ../location_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
